version: '3'
services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=login
    networks:
      - postgres


  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - postgres
      

  backend:
    build:
      context: ./node-back
    container_name: node-back
    restart: always
    depends_on:
      - db_postgres
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db_postgres:5432/login
    volumes: 
      - ./node-back:/node-back
    networks:
      - postgres
    extra_hosts: 
      local: 0.0.0.0
        

  frontend:
    build:
      context: ./next-front
    container_name: next-front
    restart: always
    depends_on: 
      - db_postgres
      - backend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes: 
      - ./next-front:/next-front
    networks:
      - postgres
            

networks:
  postgres:
    driver: bridge